/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a7a0ced492b58db7eec45f4a3fa66409)
interface __BaseEnv_Env {
	REQUEST_LIMITER: RateLimit;
	AI_LIMITER: RateLimit;
	PLACES_LIMITER: RateLimit;
	ROUTES_LIMITER: RateLimit;
	DIAGNOSTIC_LIMITER: RateLimit;
	GEMINI_MODEL: "gemini-3.8-flash";
	ALLOWED_ORIGINS: "http://localhost:8081,http://localhost:19006";
	AUTH_MODE: "prototype";
	ENABLE_DEV_DIAGNOSTICS: "false";
	MAX_PLACE_RESULTS: "5";
	MAX_STOPS: "5";
	MAX_AI_HISTORY_MESSAGES: "12";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_MODEL" | "ALLOWED_ORIGINS" | "AUTH_MODE" | "ENABLE_DEV_DIAGNOSTICS" | "MAX_PLACE_RESULTS" | "MAX_STOPS" | "MAX_AI_HISTORY_MESSAGES">> {}
}
