/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6df64d0da06cc1d12b141169de67e683)
interface __BaseEnv_Env {
	REQUEST_LIMITER: RateLimit;
	AI_LIMITER: RateLimit;
	GEMINI_MODEL: "gemini-3.8-flash";
	ALLOWED_ORIGINS: "http://localhost:8081,http://localhost:19006";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_MODEL" | "ALLOWED_ORIGINS">> {}
}
